[project]
authors = ["ONNX Contributors <onnx-technical-discuss@lists.lfaidata.foundation>"]
channels = ["conda-forge"]
description = "Open Neural Network Exchange"
name = "onnx"
platforms = ["osx-arm64", "linux-64"]

[tasks.build]
# Some shells don't accept overwriting variables(?)
cmd = 'export CMAKE_ARGS="$CMAKE_ARGS $CMAKE_EXTRA_ARGS" && pip install --no-deps --ignore-installed --verbose --no-build-isolation .'
[tasks.gen-docs]
depends-on = "build"
cmd = "python onnx/defs/gen_doc.py"

[tasks.build.env]
ONNX_ML="1"
ONNX_BUILD_TESTS="1"
CONDA_PREFIX="${PREFIX}"
CMAKE_EXTRA_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF"

[dependencies]
c-compiler = ">=1.8.0"
cmake = ">=3.31.5"
cxx-compiler = ">=1.8.0"
libdate = ">=3.0.1,<4"
make = "*"
ml_dtypes = ">=0.5.1"
ninja = "*"
numpy = ">=2.2.2"
packaging = ">=24.1"
parameterized = ">=0.9.0"
pip = ">=25.0"
protobuf = "*"
python = ">=3.10"
setuptools = ">=75.8.0"
twine = ">=6.1.0,<7"
wheel = ">=0.45.1"
pybind11 = ">=2.13.6"
libprotobuf = "*"


[feature.test.dependencies]
nbval = ">=0.11.0"
pytest = ">=8.3.4"
pytest-cov = ">=6.0.0"
pytest-xdist = ">=3.6.1"

[feature.test.tasks.test]
cmd = "pytest tests"


[feature.lint.dependencies]
ruff = "==0.8.4"  # requirements-lintrunner.txt
mypy = "==1.14.1"  # requirements-lintrunner.txt
types-protobuf = ">=5.29.1.20241207"
clang-format = ">=19.1.5"
[feature.lint.pypi-dependencies]
lintrunner = ">=0.10.7"
lintrunner-adapters = ">=0.12.3"
editorconfig-checker = "==3.0.3"
[feature.lint.tasks]
lintrunner-init = "lintrunner init"
lintrunner-run = "lintrunner --all-files"


[environments]
# This table maps "environment names" to a list of **features**
# (i.e. not a list of other environments).  Environments and features
# may have overlapping names.
default = ["test", "lint"]
