name: conda-forge CI
on:
  push:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-install-lint:
    name: Build, install, and lint (${{ matrix.os }}, ${{ matrix.environment }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        environment:
          - default
          - oldies
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          environments: ${{ matrix.environment }}
      - name: Install repository
        run: pixi run -e ${{ matrix.environment }} install
      - name: lintrunner-init
        # Linting fails probably due to old NumPy version
        if: ${{ matrix.environment != 'oldies' }}
        run: pixi run -e ${{ matrix.environment }} lintrunner-init
      - name: lintrunner-run
        if: ${{ matrix.environment != 'oldies' }}
        run: pixi run -e ${{ matrix.environment }} lintrunner-run
      - name: gtests
        run: pixi run -e ${{ matrix.environment }} gtest
      - name: pytest
        run: pixi run -e ${{ matrix.environment }} pytest
