name: CI
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-install-lint:
    name: Build, install, and lint (${{ matrix.os }}, ${{ matrix.environment }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        environment:
          - default
          - oldies
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          submodules: true
          fetch-depth: 0
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659
        with:
          environments: ${{ matrix.environment }}
      - name: Install repository
        run: pixi run -e ${{ matrix.environment }} build
      - name: lintrunner-init
        # Linting fails probably due to old NumPy version
        if: ${{ matrix.environment != 'oldies' }}
        run: pixi run -e ${{ matrix.environment }} lintrunner-init
      - name: lintrunner-run
        if: ${{ matrix.environment != 'oldies' }}
        run: pixi run -e ${{ matrix.environment }} lintrunner-run
      - name: gtests
        run: pixi run -e ${{ matrix.environment }} gtest
      - name: pytest
        run: pixi run -e ${{ matrix.environment }} pytest
