# Copyright (c) ONNX Project Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: Pixi CI

on:
  schedule:
    # run weekly on Sunday 23:59
    - cron:  '29 23 * * SUN'
  push:
    paths:
      - '.github/workflows/pixi_build.yml'
      - 'CMakeLists.txt'
      - 'pixi.lock'
      - 'pixi.toml'

permissions:
  contents: read
  issues: write  # Needed to create an issue on failure

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  install-lint:
    name: Install and test (${{ matrix.os }}, ${{ matrix.environment }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        environment-variant:
          - oldies
          - py314
    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          environments: build-${{ matrix.environment }} run-${{ matrix.environment }}
      - name: Build repository
        run: pixi run -e build-${{ matrix.environment }} build
      - name: gtests
        run: pixi run -e build-${{ matrix.environment }} gtest
      - name: Pip-install repository
        run: pixi run -e run-${{ matrix.environment }} install
      - name: pytest
        run: pixi run -e run-${{ matrix.environment }} pytest
      - name: Issue on failure
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          script: |
            github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              labels: "[bot] pixi CI"
            }).then((issues) => {
              if (issues.data.length === 0){
                github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: "Scheduled pixi CI failed",
                  body: "The scheduled pixi-based CI failed. See https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}} for details.",
                  assignees: ["cbourjau"],
                  labels: ["[bot] pixi CI"]
                })
              }
            });
